### ISSUE TITLE
Issue description length

### ISSUE THREAD

**Issue by tambre** [tambre/fatbot#21]
Issue description length should be 2000 characters

**Comment by abirdatta** [comment]
Added the fix for this issue. Amazon lex wasn't able to put the provided big description value to the slot. Had to put that manually from lambda code.

**Comment by abirdatta** [comment]
At this moment amazon lex doesn't support more than 1024 characters in an input. Giving that - it gives and error - 
![image](https://user-images.githubusercontent.com/17510846/27792167-125c96dc-6016-11e7-9112-d0d145c4ae5c.png)
